s= set()
n = input("Input no 1 : ")
s.add(int(n))
n = input("Input no 2 : ")
s.add(int(n))
n = input("Input no 3 : ")
s.add(int(n))
n = input("Input no 4 : ")
s.add(int(n))
n = input("Input no 5 : ")
s.add(int(n))
n = input("Input no 6 : ")
s.add(int(n))
n = input("Input no 7 : ")
s.add(int(n))
n = input("Input no 8 : ")
s.add(int(n))

print(s)