# Generated by Django 5.1.4 on 2024-12-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='massage',
            new_name='message',
        ),
    ]
